### ISSUE TITLE
Photo mode post edit bug

### ISSUE THREAD

**Issue by YuliaS11** [denikson/CM3D2.YATranslator#21] opened 2018-06-05 22:40 UTC
[Com3d2]
Been having this problem for a long time, but can confirm now that YATranslator prevents pose edit menu from working.

**Comment by ghorsington** [comment] 2018-06-06 04:34
Sounds like a duplicate of #20.

Please elaborate more if the issue is totally unrelated to #20.

**Closed as completed by ghorsington** 2018-06-06 04:34 UTC
Labels: duplicate

**Comment by YuliaS11** [comment] 2018-06-06 19:41
Cannot you put this on the common issue and solution page?

**Comment by ghorsington** [comment] 2018-06-06 21:24
That is indeed a fine idea! I updated the [Troubleshooting page](https://github.com/denikson/CM3D2.YATranslator/wiki/Troubleshooting#common-issues-and-solutions) to remind to check GitHub issue tracker for common issues and solutions.  
After all, GitHub issue tracker is a place to check for common issues and solutions.

**Comment by YuliaS11** [comment] 2018-06-11 01:46
Also, do you know how to stop names from being translate?

**Comment by ghorsington** [comment] 2018-06-11 12:38
They aren't, unless you explicitly translate them.   
However, if you have AutoTranslate installed, it will translate anything it sees -- including names.
