### ISSUE TITLE
Edit place in Pose Edit is stuck in the legs editing

### ISSUE THREAD

**Issue by Liely118** [denikson/CM3D2.YATranslator#20] opened 2018-03-29 11:39 UTC
In Pose Edit, edit place is stuck in the legs editing no matter which Edit place I chose. 
![huhuhaha4](https://user-images.githubusercontent.com/31807728/38086665-6b6f0646-337f-11e8-8125-afe14cf980cd.png)

Changing the translated strings back to Japanese in google_translated.txt seems to make it works again. Could this be some kinds of problem like #2?

![huhuhaha4-5](https://user-images.githubusercontent.com/31807728/38088475-27a6f7d2-3386-11e8-908f-4d8b4fa517eb.png)

COM3D2 v.1.08.0 -- Sybaris 1.0 -- YATranslator 1.5.3.0

**Comment by ghorsington** [comment] 2018-03-29 17:25
This is a known issue and only partially related to #2 and #18. 
I have replied to it a long time ago on [HongFire](http://www.hongfire.com/forum/forum/hentai-lair/hf-modding-translation/custom-maid-3d-2-mods/5813782-plugin-yat-yet-another-translator-1-4-2-0-subtitles?p=5818399#post5818399), so I'll just recap the whole thing so it can be referenced in future issues. You can read the whole comment thread for some in-detail info.

Shortly put, the problem is exactly the same as in #2 (or #16). However, since these kind of problems are plentiful in the game (thanks, devs), patching them all is simply pointless.

Instead, use level/string ignore provided by AutoTranslate 1.3.x (get it if you don't have it). 
In `UnityInjector\Config`, create a file called `AutoTranslateIgnore.txt` and add the following strings to ignore (one per line):

```
足
手
胴体
```

*Alternatively*, you can ignore the whole photo mode UI:

```
$LEVEL 27
```

After saving the ignore file, remove `google_translated.txt`.

Next time you open the photo mode, all but those buttons are translated (or nothing is if you disabled the whole level). Though since there are bound to exist more such broken buttons, I prefer the latter option (disabling translation for the whole level).

Closing this since there is nothing to fix for now. If you do have questions, feel free to still post them here.

**Closed as completed by ghorsington** 2018-03-29 17:25 UTC
Labels: wontfix
